# Generated by Django 5.0.1 on 2025-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="ai_itinerary",
            field=models.TextField(
                blank=True,
                help_text="Stores the AI-generated itinerary for the trip",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="itinerary_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when itinerary was generated",
                null=True,
            ),
        ),
    ]
